Models/Summernote.cs
namespace webmvc.Models
{
    public class Summernote 
    {
        public Summernote(string iDEditor, bool loadLibrary  = true)
        {
            IDEditor = iDEditor;
            LoadLibrary = loadLibrary;
        }

        public string IDEditor { get; set; }

        public bool LoadLibrary { get; set; }

        public int height { get; set; } = 120;

        public string toolbar { get; set; } = @"
            [
                ['style', ['style']],
                ['font', ['bold', 'underline', 'clear']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
                ['insert', ['link', 'picture', 'video', 'elfinder']],
                ['height', ['height']],
                ['view', ['fullscreen', 'codeview', 'help']]
            ]       
        ";
    }
}

Areas/Blog/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using webmvc.Models;
using webmvc.Models.Blog;
using Microsoft.AspNetCore.Identity;
using webmvc.Utilities;

using webmvc.Areas.Blog.Models;

namespace webmvc.Areas.Blog.Controllers
{
    public class PostController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _appUser;

        public PostController(AppDbContext context, UserManager<AppUser> appUser)
        {
            _context = context;
            _appUser = appUser;
        }
        [TempData]
        public string StatusMessage {get;set;}

        // GET: Post
        public async Task<IActionResult> Index([FromQuery(Name ="p")]int currenpage, int pagesize)
        {
          var post = _context.posts.Include(c=>c.Author)
                    .OrderByDescending(p=> p.DateUpdated);
                    int totalPost = await post.CountAsync();
                    if(pagesize <= 0)   pagesize =10;
                    int countPages = (int)Math.Ceiling((double)totalPost / pagesize);  

                    if(currenpage > countPages) currenpage = countPages;
                    if(currenpage < 1) currenpage =1; 

                    var pagingModel = new PagingModel()
                    {
                        currentpage = currenpage,
                        countpages = countPages,
                        generateUrl = (pageNumber) => Url.Action("Index", new {
                                p = pageNumber,
                                pagesize =pagesize
                        })
                    };
                    ViewBag.pagingModel = pagingModel;
                    ViewBag.totalPost = totalPost;
                    ViewBag.PostIndex = (currenpage -1) *pagesize;

                    var postInPage = await post.Skip((currenpage - 1) * pagesize)
                            .Take(pagesize)
                            .Include(p => p.PostCategories)
                            .ThenInclude(pc=> pc.category).ToListAsync();
                           
                //  model.totalUsers = await qr.CountAsync();
                // model.countPages = (int)Math.Ceiling((double)model.totalUsers / model.ITEMS_PER_PAGE);

                // if (model.currentPage < 1)
                //     model.currentPage = 1;
                // if (model.currentPage > model.countPages)
                //     model.currentPage = model.countPages;

                // var qr1 = qr.Skip((model.currentPage - 1) * model.ITEMS_PER_PAGE)
                //             .Take(model.ITEMS_PER_PAGE)
                //             .Select(u => new UserAndRole() {
                //                 Id = u.Id,
                //                 UserName = u.UserName,
                //             });
        
            
            return View( postInPage);
        }

        // GET: Post/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.posts
                .Include(p => p.Author)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Post/Create
        public async Task< IActionResult> Create()
        {
           var category = await _context.categories.ToListAsync();
           new MultiSelectList(category, "Id","Title");
           ViewData["categories"] = new MultiSelectList(category, "Id","Title");
            return View();
        }

        // POST: Post/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Descreption,Slug,Content,Published,categoryID ")] CreatePostModel post)
        {
               var category = await _context.categories.ToListAsync();
             ViewData["categories"] = new MultiSelectList(category, "Id","Title");
              if(post.Slug == null)
              {
                post.Slug = AppUtilities.GenerateSlug(post.Title);
              }

              if (await _context.posts.AnyAsync( p=> p.Slug == post.Slug)) 
              {
                ModelState.AddModelError("Slug", "Nhập chuỗi ký tự khác");
                return View(post);
              }
            if (ModelState.IsValid)
            {
             
             
                var user = await _appUser.GetUserAsync(this.User);
                 post.DateCreated = post.DateUpdated = DateTime.Now;

                  post.AuthorId = user.Id; 
                  
                _context.Add(post);

                if(post.categoryID != null)
                {   
                    foreach (var cateID in post.categoryID)
                    {
                        _context.Add(new PostCategory(){
                            categoryID  = cateID,
                            post = post
                        });
                    }
                }
                await _context.SaveChangesAsync();
                StatusMessage = " Vua tao bai viet moi";
                return RedirectToAction(nameof(Index));
            }
          
            return View(post);
        }

        // GET: Post/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // var post = await _context.posts.FindAsync(id);
            var post = await _context.posts.Include(p=> p.PostCategories).FirstOrDefaultAsync(p=>p.ID == id);
            if (post == null)
            {
                return NotFound();
            }
            var postEdit = new CreatePostModel()
            {
                 ID = post.ID,
                Title = post.Title,
               
                Content = post.Content,
                Descreption = post.Descreption,
                Slug = post.Slug,
                Published = post.Published,
                categoryID = post.PostCategories.Select(pc => pc.categoryID).ToArray()

            };
             var category = await _context.categories.ToListAsync();
             ViewData["categories"] = new MultiSelectList(category, "Id","Title");
            return View(postEdit);
        }

        // POST: Post/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,Descreption,Slug,Content,Published,categoryID")] CreatePostModel post)
        {
            if (id != post.ID)
            {
                return NotFound();
            }

            var category = await _context.categories.ToListAsync();
             ViewData["categories"] = new MultiSelectList(category, "Id","Title");
               if(post.Slug == null)
              {
                post.Slug = AppUtilities.GenerateSlug(post.Title);
              }

              if (await _context.posts.AnyAsync( p=> p.Slug == post.Slug)) 
              {
                ModelState.AddModelError("Slug", "Nhập chuỗi ký tự khác");
                return View(post);
              }

            if (ModelState.IsValid)
            {
                try
                {
                    var postUpdate = await _context.posts.Include(p=> p.PostCategories).FirstOrDefaultAsync(p=>p.ID == id);
                   if(postUpdate == null)
                   {
                         return NotFound();
                   }
                  postUpdate.Title = post.Title;
                  postUpdate.Descreption = post.Descreption;
                   postUpdate.Content = post.Content;
                    postUpdate.Published = post.Published;
                     postUpdate.Slug = post.Slug;
                      postUpdate.DateUpdated = DateTime.Now;

                    if(post.categoryID == null) post.categoryID = new int []{};

                    var oldCateId = postUpdate.PostCategories.Select(c =>c.categoryID).ToArray();
                    var newCateIDS = post.categoryID;
                      var removeCatePosts = from PostCategory in postUpdate.PostCategories
                                          where (!newCateIDS.Contains(PostCategory.categoryID))
                                          select PostCategory;
                    _context.postCategories.RemoveRange(removeCatePosts);

                    var addCateIds = from CateId in newCateIDS
                                     where !oldCateId.Contains(CateId)
                                     select CateId;

                     foreach (var CateId in addCateIds)
                     {
                         _context.postCategories.Add(new PostCategory(){
                             postID = id,
                             categoryID = CateId
                         });
                     }      

                    _context.Update(postUpdate);

                    await _context.SaveChangesAsync();
                }


                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

Controllers/PlanetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using webmvc.Services;
using Microsoft.Extensions.Logging;

namespace webmvc.Controllers
{
    public class PlanetController : Controller
    {
        private readonly  PlanetServices _planetServices;
         private readonly ILogger<FirstController> _logger;

        public PlanetController(ILogger<FirstController> logger,    PlanetServices planets){
            _logger = logger;
            _planetServices = planets ;
        }

        [Route("danhsachcachanhtinh.html")]
        public IActionResult Index()
        {
            return View();
        }
        
        // route : action
        [BindProperty(SupportsGet = true, Name = "action")]
        public string Names{get;set;}
        public IActionResult Mercury() // khi truy cap action Mercury se co Name = Mercury, ten action == ten PlanetModel
        {
           var planet = _planetServices.Where(p =>p.Name == Names).FirstOrDefault();
            return View("Detail", planet);
        }
        
        public IActionResult Venus()
        {
             var planet = _planetServices.Where(p =>p.Name == Names).FirstOrDefault();
            return View("Detail", planet);
        }
        
        public IActionResult Earth()
        {
             var planet = _planetServices.Where(p =>p.Name == Names).FirstOrDefault();
            return View("Detail", planet);
        }
        
        public IActionResult Mars()
        {
            var planet = _planetServices.Where(p =>p.Name == Names).FirstOrDefault();
            return View("Detail", planet);
        }
        [HttpGet("/saomoc.html")]
        public IActionResult Jupiter()
        {
             var planet = _planetServices.Where(p =>p.Name == Names).FirstOrDefault();
            return View("Detail", planet);
        }
        
        public IActionResult Saturn()
        {
             var planet = _planetServices.Where(p =>p.Name == Names).FirstOrDefault();
            return View("Detail", planet);
        }
        
        public IActionResult Uranus()
        {
            var planet = _planetServices.Where(p =>p.Name == Names).FirstOrDefault();
            return View("Detail", planet);
        }
        
        public IActionResult Neptune()
        {
            var planet = _planetServices.Where(p =>p.Name == Names).FirstOrDefault();
            return View("Detail", planet);
        }
         public IActionResult Comet()
        {
             var planet = _planetServices.Where(p =>p.Name == Names).FirstOrDefault();
            return View("Detail", planet);
        }

    }
}

Views/Shared/_AlertMessage.cshtml
@{
    var message = TempData["StatusMessage"] as string;
}
@if (!string.IsNullOrEmpty(message))
{
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    @message
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - webmvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">webmvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planet" asp-action="Index">He Mat Troi</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Contact" asp-controller="Contact" asp-action="SendContact">Liên hệ</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial"></partial>
                    <partial name="_MenuManagePartial"></partial>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - webmvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuManagePartial.cshtml
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Manage
  </button>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" asp-action="Index" asp-controller="DbManager" asp-area="Database">Database</a>
    <a class="dropdown-item" asp-action="Index" asp-controller="Contact" asp-area="Contact">Lien He</a>
     <a class="dropdown-item" asp-action="Index" asp-controller="Role" asp-area="Identity">Quan Ly (role)</a>
      <a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Identity">Quan ly (User)</a>
      <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Blog">Quản Lý Blog</a>
      <a class="dropdown-item" asp-action="Index" asp-controller="Post" asp-area="Blog">Quản Lý Bài Viết Blog</a>
  
  </div>
</div>

Views/Shared/_PagingXTL.cshtml
@* 
    Model:
      - currentPage:int - Trang hiện tại
      - countPages:int - tổng số trang
      - generateUrl:delegate Func<int?, string> trả về URL tương ứng với trang p (1,2,3 ...)
*@

@model webmvc.Models.PagingModel
@{
    int currentPage  = Model.currentpage;
    int countPages   = Model.countpages;
    var generateUrl  = Model.generateUrl;


    
    if (currentPage > countPages) 
      currentPage = countPages;

    if (countPages <= 1) return;
    

    int? preview = null;
    int? next = null;

    if (currentPage > 1)
        preview = currentPage - 1;

    if (currentPage < countPages)
        next = currentPage + 1;

    // Các trang hiện thị trong điều hướng
    List<int> pagesRanges = new List<int>();    

        
    int delta      = 5;             // Số trang mở rộng về mỗi bên trang hiện tại     
    int remain     = delta * 2;     // Số trang hai bên trang hiện tại

    pagesRanges.Add(currentPage);
    // Các trang phát triển về hai bên trang hiện tại
    for (int i = 1; i <= delta; i++)
    {
        if (currentPage + i  <= countPages) {
            pagesRanges.Add(currentPage + i); 
            remain --;
        }
               
        if (currentPage - i >= 1) {
            pagesRanges.Insert(0, currentPage - i);
            remain --;
        }
            
    }    
    // Xử lý thêm vào các trang cho đủ remain 
    //(xảy ra ở đầu mút của khoảng trang không đủ trang chèn  vào)
    if (remain > 0) {
        if (pagesRanges[0] == 1) {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.Last() + 1 <= countPages) {
                    pagesRanges.Add(pagesRanges.Last() + 1);
                }
            }
        }
        else {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.First() - 1 > 1) {
                    pagesRanges.Insert(0, pagesRanges.First() - 1);
                }
            }
        }
    }

}

@* PHÁT SINH HTML*@

<ul class="pagination">
    <!-- Previous page link -->
    @if (preview != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(preview)">Trang trước</a>
        </li>
    }
    else
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang trước</a>
        </li>
    }
      
    <!-- Numbered page links -->
    @foreach (var pageitem in pagesRanges)
    {
        if (pageitem != currentPage) {
            <li class="page-item">
                <a class="page-link" href="@generateUrl(pageitem)">
                    @pageitem
                </a>
            </li>
        }   
        else 
        {
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">@pageitem <span class="sr-only">(current)</span></a>
            </li>
        }
    }


    <!-- Next page link -->
    @if (next != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(next)">Trang sau</a>
        </li>
    }
    else 
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang sau</a>
        </li>
    }
</ul>

Views/Shared/_StatusMessage.cshtml
@{
    var mgs = TempData["StatusMessage"] as string;
}

@if (!String.IsNullOrEmpty(mgs))
{
    var statusMessageClass = mgs.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @mgs
    </div>
}

Views/Shared/_Summernote.cshtml
@model webmvc.Models.Summernote

@if (Model.LoadLibrary)
{
    <script src="~/lib/summernote/summernote-bs4.min.js"></script>
    <link rel="stylesheet" href="~/lib/summernote/summernote-bs4.min.css" />

  
    
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/lib/elfinder/js/elfinder.min.js"></script>       
}


<script>

   



    $(document).ready(function(){
        $('@Model.IDEditor').summernote({
            height: @Model.height,
            toolbar: @Html.Raw(Model.toolbar)
        });
    });  
</script>